Babel Routing (#1895)
* Babel

* Fixes

* Add reporting, restarts, and upgades supports

* Babel & AREDNLink demo

* Get babel routes

* Config

* Integration

* Modify upgrade backups to capture babel state

* arednlink-dump

* Improve command line firmware updating

* Whitespace

* No init.d for socat (just want the app)

* Babel

* getRoutableNeighbors

* Set local path

* Fix babel restart

* Routing

* Table 21

* babeld -> babel

* arednlink reload

* supernode

* Add ipv6 linklocal address to wireguard tunnels

* Improve postfix handling

* fix

* More debug info

* Use rtnl.request

* Report babel routes

* new tables

* More support data

* Simplify supenode rules and routes

* Renamed arednlink-reload

* Handle failure to connect to babel

* Move directories

* List babel nodes

* fix

* fix

* fix

* Files moves into babel package

* Make weight available for network.wireguard

* Rework radio setup

* Rework wifi configuration

* Babel

* Fixes

* Add reporting, restarts, and upgades supports

* Babel & AREDNLink demo

* Get babel routes

* Config

* Integration

* Modify upgrade backups to capture babel state

* arednlink-dump

* Improve command line firmware updating

* Whitespace

* No init.d for socat (just want the app)

* Babel

* getRoutableNeighbors

* Set local path

* Fix babel restart

* Routing

* Table 21

* babeld -> babel

* arednlink reload

* supernode

* Add ipv6 linklocal address to wireguard tunnels

* Improve postfix handling

* fix

* More debug info

* Use rtnl.request

* Report babel routes

* new tables

* More support data

* Simplify supenode rules and routes

* Renamed arednlink-reload

* Handle failure to connect to babel

* Move directories

* List babel nodes

* fix

* fix

* fix

* Files moves into babel package

* Make weight available for network.wireguard

* improve

* txpower

* Use nl80211 api

* Tweak wording

* Protect getting wireless interface info

* Improve supernode status reporting layout

* Unused config in mesh sta

* Add lqm babel port blocking

* Reduce max AREDN SSID size to include AREDN extension

* SNR limits reflected in wifi setup

* Keep channel and chanbw in meshsta

* LQM blocking is off during Babel testing
Leave range finding and hidden node detection enabled.

* Improve LQM for Babel (just honor user actions)

* Fix year

* Add missing domain

* Add icon to signify nodes using babel routes

* Fix some minor layout issues

* Mesh AP -> Mesh PtMP (to allow Mesh PtP later)

* Track babel on supernodes

* Tweak text

diff --git a/files/usr/local/bin/aredn_sysupgrade b/files/usr/local/bin/aredn_sysupgrade
--- a/files/usr/local/bin/aredn_sysupgrade
+++ b/files/usr/local/bin/aredn_sysupgrade
@@ -1,6 +1,7 @@
+#!/bin/sh
 true <<'LICENSE'
   Part of AREDN® -- Used for creating Amateur Radio Emergency Data Networks
-  Copyright (C) 2022 Tim Wilkinson
+  Copyright (C) 2025 Tim Wilkinson
   See Contributors file for additional contributors
 
   This program is free software: you can redistribute it and/or modify
@@ -32,6 +33,16 @@ true <<'LICENSE'
 
 LICENSE
 
+if [ "$#" != "1" ]; then
+  echo "Usage: aredn_sysupgrade <firmwarefile>" 1>&2
+  exit 1
+fi
+
+if [ ! -f "$1" ]; then
+  echo "ERROR: Missing firmware file: $1" 1>&2
+  exit 1
+fi
+
 #
 # Pre-upgrade special cases
 #
@@ -50,11 +61,45 @@ case "$(/usr/local/bin/get_boardid)" in
 esac
 
 #
+# Generate the backup
+#
+backup="-n"
+if [ ! -f /tmp/do-not-keep-configuration ]; then
+  # Stop babel if it's installed.
+  # We need to do this here so we get the state information into the backup file.
+  if [ -f /etc/init.d/babel ]; then
+    /etc/init.d/babel stop
+    sleep 1 # Give it a moment or three to stop
+    if [ ! -f /etc/state/babel-state ]; then
+      sleep 2
+    fi
+  fi
+  cp /dev/null /tmp/sysupgradefilelist
+  cat /etc/arednsysupgrade.conf | while read f
+  do
+    if [ -f "${f}" ]; then
+      echo "${f}" >> /tmp/sysupgradefilelist
+    fi
+  done
+  rm -f /tmp/arednsysupgradebackup.tgz
+  tar -czf /tmp/arednsysupgradebackup.tgz -T /tmp/sysupgradefilelist > /dev/null 2>&1
+  if [ -f /tmp/arednsysupgradebackup.tgz ]; then
+    backup="-f /tmp/arednsysupgradebackup.tgz"
+  else
+    if [ -f /etc/init.d/babel ]; then
+      /etc/init.d/babel start
+    fi
+    echo "ERROR: Failed to create backup - aborting firmware upgrade" 1>&2
+    exit 1
+  fi
+fi
+
+#
 # Let users force upgrade a node
 #
 force=""
-if [ -f /tmp/force-upgrade-this-is-dangerous ]; then
+if [ -f "/tmp/force-upgrade-this-is-dangerous" ]; then
   force="--force"
 fi
 
-/sbin/sysupgrade ${force} $*
+/sbin/sysupgrade ${force} ${backup} -q "$1"
